### ISSUE TITLE
Feature request: image ( file ) upload

### ISSUE THREAD

**Issue by thhck** [ULB-Darmstadt/shacl-form#8]
Hi , 

It would be a great to be able to upload a file. 

However I'm not sure how to implement it. 

In javascript, <input type="file"..> return directly a File object. This won't be possible with shacl-form, but maybe the form can return some primitive that allow to create the javascript file object afterward ?

**Comment by s-tittel** [comment]
Hi, there are a couple of options for that:

1. Version 1.4.1 now supports the datatype [xsd:base64Binary](https://www.w3.org/TR/xmlschema11-2/#base64Binary) and renders an `<input type="file">` element for that. So if you define a SHACL property with that datatype in the shapes graph, you will get the base64 encoded **data URL** in the data graph. I have tested that successfully with files up to ~500 kB, larger files will lead to an error during validation due to too much recursion (within the [library](https://github.com/zazuko/rdf-validate-shacl) that I use for that).
2. Create a [plugin](https://github.com/ULB-Darmstadt/shacl-form?tab=readme-ov-file#plugins) for that. You could register your plugin for the RDF predicate that you use in your shapes graph for the file. Your plugin could then handle the file upload itself in any way you prefer.
3. Modify the form with JavaScript at runtime,  basically inserting an `<input type="file">` element at the position you desire.

**Comment by s-tittel** [comment]
Plugin has been merged
